add components
Rim-777/blog_platform pull request #1
Opened 2017-05-26 17:55 UTC by Rim-777

С серверным рендерингом все ок.  в jsbin тоже все работает:  http://jsbin.com/bibasucidi/1/edit?html,js,console,output  
Без сервера, как я понимаю в силу отсутствия сборки, и  вывести компоненты на страницу не удастся.

2017-05-27 08:14 UTC, index01d requested changes

2017-05-27 08:14 UTC, index01d commented on components/containers/BlogList.js
> +        return (
дело вкуса, но чаще принято 2 пробела в качестве отступок

2017-05-27 08:14 UTC, index01d commented on components/containers/BlogList.js
> +                    {<BlogItem textBoxContent={item.textBoxContent} imgAttr={item.imgAttr}/>}
лучше передавать весь объект с записью компоненту без деструктурирования

2017-05-27 08:14 UTC, index01d commented on components/containers/BlogList.js
> +                    {<BlogItem textBoxContent={item.textBoxContent} imgAttr={item.imgAttr}/>}
также в названиях лучше избегать избыточных определений и давать хорошие английские имена: imgAttr -> image (это чисто субъективное стилистическое замечание относительно читаемости кода)

2017-05-27 08:14 UTC, index01d commented on components/ui/BlogItem.js
> +        <Image attr={props.imgAttr}/>
Здесь лучше передавать конкретные свойства (width, height, alt, src) без собственно придуманных свойств:) Тогда пользователю компонента будет интуитивно проще разобраться с интерфейсом

2017-05-27 11:17 UTC, Rim-777 commented on components/containers/BlogList.js
> +        return (
Насколько это принципиально для комьюнити? Посмотрел код программистов из команды Ильи Кантера (learn.javascript)  - они делают один отступ. Собственно как бэкэндщик, тоже считаю что один отступ выглядит логичнее... Но если это реально общее правило то буду как все)))

2017-05-27 11:35 UTC, index01d commented on components/containers/BlogList.js
> +        return (
лично мне непринципиально совсем, просто тренд 2 пробела:)

2017-05-27 11:35 UTC, index01d approved these changes

2017-05-27 11:37 UTC, Rim-777 commented on components/containers/BlogList.js
> +        return (
тогда можно уточнить, два пробела везде, то есть внутри компонента и  отступ от импортов и экспорт - тоже два пробела, или только внутри компонента?

2017-05-28 14:01 UTC, index01d commented
речь идет об инденте а не отступе между строками если что

2017-05-30 20:06 UTC, merged