add likes
Rim-777/blog_platform pull request #2
Opened 2017-06-02 12:00 UTC by Rim-777

2017-06-03 08:46 UTC, index01d requested changes

2017-06-03 08:46 UTC, index01d commented on components/ui/Author.js
> +        {`Author: ${data && data.firstName} ${data && data.lastName}`}
можно использовать get из lodash (или альтернативу, вплоть до своего хелпера), тогда будет просто get(data, 'firstName'). Низкоуровневый код в презентационных компонентах выглядит очень плохо и ухудшает читаемость.

Также лучше избегать лишнего ключа data, почему бы не передавать firstName, lastName (семантически название data не дает никакого представления о содержимом)?

2017-06-03 08:46 UTC, index01d commented on components/ui/Author.js
> +        {`Author: ${data && data.firstName} ${data && data.lastName}`}
кроме того, проверка не совсем корректно сделана, тк будут лишние пробелы, если нет одного из ключей

2017-06-03 08:46 UTC, index01d commented on components/ui/BlogItem.js
> +                /><br/>
br :(

2017-06-03 08:46 UTC, index01d commented on components/ui/BlogItem.js
> +        image:React.PropTypes.shape({
можно утащить к компоненту Image и реиспользовать Image.propTypes здесь, тогда не придется дублировать в каждом месте, где будет исползоваться Image

2017-06-03 08:46 UTC, index01d commented on components/ui/Likes.js
> +                {`likes: ${this.state.amount}`}
div не закрыт

2017-06-03 08:46 UTC, index01d commented on components/ui/Likes.js
> +        this.state = {amount: this.props.amount || 0}
можно использовать defaultProps, тогда не понадобится оператора здесь

2017-06-03 08:46 UTC, index01d commented on components/ui/Timestamps.js
> +          {`created at: ${dateTime && moment(dateTime.createdAt).format('MM/DD/YYYY hh:mm') || ''}`}
форматирование и формат лучше вынести в отдельную функцию, чтобы можно было глобально управлять временем и оставалась возможность безболезненно заменить низкоуровневую библиотеку (moment)

2017-06-03 08:46 UTC, index01d commented on components/ui/Timestamps.js
> +          {`created at: ${dateTime && moment(dateTime.createdAt).format('MM/DD/YYYY hh:mm') || ''}`}
кроме того, можно будет устранить некрасивый datetime && из презентационного компонента

2017-06-03 08:46 UTC, index01d commented on components/ui/BlogItem.js
> +            author:React.PropTypes.shape({
можно унести к компоненту Author (см ниже комментарий про картинку)

2017-06-03 08:46 UTC, index01d commented on components/ui/BlogItem.js
> +            timestamps: React.PropTypes.shape({
можно унести к компоненту timestamps (см ниже комментарий про картинку)

2017-06-03 09:08 UTC, index01d requested changes
Набросал свой вариант (схематично, конечно же) того же компонента но с некоторыми изменениями, улучшающими читаемость.

```
import React from 'react';

import PropTypes from 'prop-types';

import { pick } from 'lodash/object';

import Author from './Author';
import TextBox from './TextBox';
import Image from './Image';
import Likes from './Likes';
import Timestamps from './Timestamps';

const BlogItem = ({ item })=>{
  const {
    title,
    metaData: {
      id = 0,
      author: { firstName, lastName } = {},
      timestamps: { createdAt, updatedAt } = {},
    } = {},
    image,
    likes
  } = props.item || {};

  return(
    <Container>
      <Author firstName={firstName} lastName={lastName} />
      <TextBox title={title} />
      <Image {...pick(image, ['src', 'width', 'style'])} />
      <Likes likes={likes} />
      <Timestamps createdAt={createdAt} updatedAt={updatedAt} />
    </Container>
  )
};

BlogItem.propTypes = {
  item: PropTypes.shape({
    metaData: PropTypes.shape({
      id: PropTypes.number.isRequired,
      author: PropTypes.shape(Author.propTypes),
      timestamps: PropTypes.shape({Timestamps.propTypes})
    }),
    title: PropTypes.string.isRequired,
    image: PropTypes.shape(Image.propTypes).isRequired
  })
};

export default BlogItem;

const Container = ({ children }) => (
  <div
    className='blogItem'
    style={{ border: "1px solid green" }}
  >
    {children}
  </div>
);
```

2017-06-03 09:08 UTC, index01d commented on components/ui/BlogItem.js
> +    const {content} = props;
просится переименование в item

2017-06-03 11:49 UTC, Rim-777 commented on components/ui/Author.js
> +        {`Author: ${data && data.firstName} ${data && data.lastName}`}
> Ок, тогда скажи как правильно делать проверку, чтобы избежать пробелов...?

2017-06-03 11:50 UTC, Rim-777 commented on components/ui/BlogItem.js
> +                /><br/>
> Так же думаю имеет смысл объяснить почему  br - не айс?

2017-06-03 11:59 UTC, Rim-777 commented on components/ui/BlogItem.js
> +            author:React.PropTypes.shape({
> Не вопрос, все PropTypes так и хотел сделать, но фраза из дз: - "Задать описание типов propTypes ...... для всех компонентов страницы блога"  для меня  выглядит, как  задатать  propTypes на странице блога...  Например "Задать описание типов propTypes для всех компонентов"  - на мой взгляд выглядело бы понятнее

2017-06-03 12:01 UTC, Rim-777 commented on components/ui/Likes.js
> +                {`likes: ${this.state.amount}`}
> Посмотри внимательней))))

2017-06-03 12:03 UTC, Rim-777 commented on components/ui/Timestamps.js
> +          {`created at: ${dateTime && moment(dateTime.createdAt).format('MM/DD/YYYY hh:mm') || ''}`}
> не совсем понятно, вынести в отдельный метод компонента Timestamps или сделать отдельный компонент?

2017-06-03 12:05 UTC, Rim-777 commented on components/ui/BlogItem.js
> +    const {content} = props;
Согласен, и за пример глубокой диструкции МЕРСИ.  Даже нигде не видел раньше, что так можно...)))

2017-06-03 12:28 UTC, Rim-777 commented on components/ui/BlogItem.js
> +    const {content} = props;
Ты в своем примере id не передал в Container ...

2017-06-03 15:45 UTC, index01d commented on components/ui/Timestamps.js
> +          {`created at: ${dateTime && moment(dateTime.createdAt).format('MM/DD/YYYY hh:mm') || ''}`}
просто сделать функцию форматирования даты, formatDate например.

2017-06-03 15:45 UTC, index01d commented on components/ui/Likes.js
> +                {`likes: ${this.state.amount}`}
ok:)

2017-06-03 15:47 UTC, index01d commented on components/ui/BlogItem.js
> +                /><br/>
потому что его принято использовать для разметки в тексте, а не для имитации поведения Image как блока. В данном случае необходимо свойство display: block.

2017-06-03 15:47 UTC, index01d commented on components/ui/Author.js
> +        {`Author: ${data && data.firstName} ${data && data.lastName}`}
ну ты хотя бы попробуй для начала сам?:) а там я поправлю, если что

2017-06-03 15:48 UTC, index01d commented on components/ui/BlogItem.js
> +    const {content} = props;
а я не поймал зачем он нужен, поэтому не передал

2017-06-05 03:08 UTC, blackleadsu requested changes

2017-06-05 03:08 UTC, blackleadsu commented on components/ui/Author.js
> +        {`Author: ${firstName || ''} ${lastName || ''}`}
1) технически, эту проверку лучше заменить на defaultProps
2) логически же правильно будет писать что автор не указан или вообще возвращать null, если и имя, и фамилия пусты (иначе на странице будет "Аuthor: "). В первом случае подойдет тернарный оператор, во втором проверка через &&
```
const Author = ({firstName, lastName}) =>( 
  (firstName || lastName) &&
  ...
);
```

2017-06-05 03:08 UTC, blackleadsu commented on components/ui/Timestamps.js
> +    created_at: PropTypes.string.isRequired,
Настойчивая рекомендация использовать camelCase везде, и в ключах тоже (в компоненте при этом createdAt).

2017-06-05 03:08 UTC, blackleaden commented on components/ui/Timestamps.js
> +              {`last update: ${_formatDate(updatedAt)}`}
Как поведет себя компонент в случае если updatedAt будет передано undefined?
Будет выведена фраза "last update: ". Что явно не корректно, при том что пост, который не обновлялся -- это норма (потому и не isRequired, верно?).

2017-06-05 06:23 UTC, Rim-777 commented on components/ui/Timestamps.js
> +    created_at: PropTypes.string.isRequired,
сорри, по привычке... исправлю

2017-06-05 06:26 UTC, Rim-777 commented on components/ui/Author.js
> +        {`Author: ${firstName || ''} ${lastName || ''}`}
А в общем то считаю, что если и возникла такая ситуация, когда данные  данные пришли пустые, то поле Автор должно остаться, даже если оно пустое...

2017-06-05 06:33 UTC, Rim-777 commented on components/ui/Timestamps.js
> +              {`last update: ${_formatDate(updatedAt)}`}
в принципе такая же ситуация,  если пост не обновлялся,но поле update обязательно то можно и оставить его пустым... Но тут возражать не буду... переделаю, ну уж точно не повод зарубать дз и тем самым терять еще день...  И если можно, пусть меня Эдуард ведет... Ничего личного, но мне как-то он ближе по духу

2017-06-05 07:05 UTC, blackleaden commented on components/ui/Author.js
> +        {`Author: ${firstName || ''} ${lastName || ''}`}
Если поле автор пустое, можно ставить значение по умолчанию "anonimus", "unknown", или прочерк.
Если нам нечего вывести в значении поля, мы должны либо не выводить поле совсем, либо явно об этом сказать "Автор: данных нет".
Во-первых, пустое значение смотрится как поломка (зачем выводить поле тогда?).
Во-вторых, гораздо презентабельнее и дружелюбнее написать, например, "Комментариев нет" вместо "Комментарии: 0".

2017-06-05 07:07 UTC, blackleaden commented on components/ui/Timestamps.js
> +              {`last update: ${_formatDate(updatedAt)}`}
см. выше. 
Если данных нет, об этом нужно написать явно и грамотно -- пустота после двоеточия всё-таки не айс)

2017-06-05 07:26 UTC, index01d commented on components/ui/Timestamps.js
> +              {`last update: ${_formatDate(updatedAt)}`}
> пусть меня Эдуард ведет... Ничего личного, но мне как-то он ближе по духу
да-да да, просто я в воскресенье отсутствовал, попросил @blackleaden  выручать:)

2017-06-05 09:06 UTC, Rim-777 commented on components/ui/Author.js
> +        {`Author: ${firstName || ''} ${lastName || ''}`}
Денис, я понимаю твое мнение, и по большому счету согласен. Но если ты посмотришь на переписку, то увидишь, что мы обсуждаем user experience. То есть это не техника написания кода. А я, как и многие другие на этом курсе уже далеко не новички, и работаем с реальными проектами. Собственно я здесь для того, чтобы освоить реакт и его экосистему.  Поэтому считаю  user experience  в данный момент в этом учебном проекте это не так уж и важен. (Я например вообще считаю, что UpdatedAt - не нужно показывать в постах, не вижу смысла. А когда нет комментариев, то достаточно просто поле для ввода нового комментария, без дополнительного разъяснения,  что комментариев нет "Для тех кто не понял)))".  ) Но, если ты считаешь user experience  - важной частью обучения, я не против, но только в этом случае пожалуйста пропиши это четко в ДЗ.  В данной ситуации я переживаю лишь за время, которое теряю в ожидании проверки. Нет его - свободного времени))), работа, собственные проекты, плюс обучение на курсе... к тому же в конце июля отпуск, и я вообще в доступе к интернету не буду. Так что хочется  успеть закончить курс пораньше...

2017-06-05 10:00 UTC, blackleaden commented on components/ui/Author.js
> +        {`Author: ${firstName || ''} ${lastName || ''}`}
Ты абсолютно прав, и не все рекомендации обязательны, и времени нет делать из учебного проекта идеальный. Раз уж мы начали обсуждать оставлять ли поле пустым -- я поделился мнением) Всё-таки интерфейсы делаем.
Жалко что не так поняли друг друга, надо будет помечать что обязательно для задания, а что - рекомендация. Спасибо тебе за отзыв!

2017-06-10 19:42 UTC, merged