customized webpack eslint etc
Rim-777/blog_platform pull request #4
Opened 2017-06-16 22:08 UTC by Rim-777

у меня Eslint выдает ошибку синтаксиса на функции стрелки в качестве методов. 
ERROR in ./src/components/containers/BlogList.js
Module build failed: SyntaxError: Unexpected token (7:12)

   5 | export default class BlogList extends Component {
   6 | 
>  7 |     getList = () => {
     |             ^
   8 |         const {items, addLike} = this.props;
   9 |         const result = items.map((item) => {
  10 |             return (

пришлось переписать.
Такая же ситуация с компонентом Timestamps он был stateless  и у него был метод, для форматирования даты. - Eslint выдал ошибку. Пришлось переделать на класс.

2017-06-18 07:31 UTC, index01d requested changes
1) В index.html нужно использовать не статически собранный dist/bundle.js (который можно удалить), а /assets/bundle.js (который вебпак собирает и пересобирает налету, не нужно будет всякий раз ходить командовать вебпаку сборку)
2) В babel.rc не соблюдаются отступы и желательно закавычить ключи
3) Со стрелочными функциями пока проблему не понял. Попробовал добавить – линтер не ругается. Пришли пожалуйста версию с ошибками
4) BlogList по определению не контейнер, а презентационный компонент для отображения списка (ни колбэков, ни обработки данных там не видно), так что не ясно что он делает в директории с контейнерами. P.S.: выделение функции getList выглядит избыточным, в render'е этот код смотрелся бы также.

2017-06-18 08:40 UTC, Rim-777 commented
Ну вот яже  поэтому и прошу проверять раньше, я в Израиле, тут воскресенье рабочий день, вчера целый день был выходной, теперь исправить смогу только вечером))

2017-06-18 19:38 UTC, index01d commented
я бы и рад проверить быстрее, но задание для проверки непростое, а я вот час назад был в минводах, щас в шереметьево, завтра буду в челябинске))) неделька выдалась плотная

2017-06-19 07:35 UTC, index01d approved these changes
Есть замечания, которые точно стоит поправить, тем не менее по заданию прув

2017-06-19 07:35 UTC, index01d commented on index.html
> +<script src="/assets/bundle.js"></script>
там выше кстати app.js, не ясно зачем он

2017-06-19 07:35 UTC, index01d commented on src/components/containers/BlogPage.js
> +import BlogList from './../ui/BlogList.js';
нужно использовать абсолютные пути вместо относительных (`import from 'components/ui/BlogList'`)

2017-06-19 07:35 UTC, index01d commented on src/components/ui/BlogList.js
> +            return (
можно избежать написания return, если использовать синтаксис
```
{items.map((item) => (
  <li style={{'listStyleType' :'none'}} key={item.metaData.id}>
     <BlogItem item={item} addLike={addLike}/>
  </li>
)}
```

2017-06-19 18:33 UTC, merged