Redux core
Rim-777/blog_platform pull request #6
Opened 2017-07-21 14:01 UTC by Rim-777

2017-07-22 10:47 UTC, index01d requested changes

2017-07-22 10:47 UTC, index01d commented on src/App.js
> +const routes = setRoutes();
код должен располагаться ниже импортов. Импорты всегда должны быть выше любого кода

2017-07-22 10:47 UTC, index01d commented on src/actions/Post.js
> +export const addLike = (id) => {
лучше сделать отдельный модуль для AC с like

2017-07-22 10:47 UTC, index01d commented on src/actions/Post.js
> +                err ? dispatch(errorPost()) : dispatch(receivePost(response.body))
вместо receivePost необходимо написать AC receiveLike или likeSuccess, который в качестве аргумента получит результат с количеством лайков и номер записи

2017-07-22 10:47 UTC, index01d commented on src/actions/Posts.js
> +export const addLike = (id) => {
лишний AC, после вынесения addLike в отдельный модуль в actions/Like.js этот код дублировать не потребуется

2017-07-22 10:47 UTC, index01d commented on src/components/containers/PostsPage.js
> +                <BlogList items={items} {...this.props} addLike={this.addLike}/>
для Like следует сделать отдельный контейнер и использовать его как `<LikeContainer id={item.id} />` в BlogItem'e, тогда BlogList и вся иерархия будут не в курсе существования этой логики. Соответственно свойство addLike здесь передаваться не будет

2017-07-22 10:47 UTC, index01d commented on src/components/ui/BlogItem.js
>              <Likes amount={likes} addLike={addLike} itemId={id}/>
Именно здесь можно импортировать LikeContainer и вместо Likes написать `<LikeContainer itemId={id} />`, коллбэк addLike тогда будет реализован в самом LikeContainer

2017-07-22 10:47 UTC, index01d commented on src/components/ui/BlogItem.js
>              <Likes amount={likes} addLike={addLike} itemId={id}/>
а amount будет передано также из контейнера в stateToProps методе LikeContainer'a

2017-07-22 10:47 UTC, index01d commented on src/components/ui/BlogList.js
> +                        <BlogItem item={item}  addLike={addLike}/>
addLike тут также не потребуется

2017-07-22 10:47 UTC, index01d commented on src/reducers/Post.js
> +        default:
здесь нужно будет добавить еще один кейс для action'a Like'a. будет нечто вроде
```
case likeTypes.FETCH_LIKE_SUCCESS:
  return assign(
    {}, 
    initialState, 
    { 
      item: assign({}, state.item, { likes: action.response.likes } })
    }
  );
```

2017-07-22 10:47 UTC, index01d commented on src/reducers/Posts.js
> +        default:
здесь нужно будет добавить еще один кейс для action'a Like'a. будет нечто вроде
```
case likeTypes.FETCH_LIKE_SUCCESS:
  return assign(
    {}, 
    initialState, 
    { 
      items: map(
        state.items, 
        (item) => item.id == action.data.itemId ? // ищем нужный пост
          assign({}, item, { likes: action.response.likes } }) // меняем в нужном количество лайков
          : item // остальные оставляем как есть
    }
  );
```

2017-07-22 10:48 UTC, index01d commented on src/actions/Post.js
> +export const addLike = (id) => {
разместить его к примеру в actions/Like.js

2017-07-23 20:40 UTC, Rim-777 commented on src/components/ui/BlogItem.js
>              <Likes amount={likes} addLike={addLike} itemId={id}/>
Не совсем понял, ты предлагаешь отказаться от компонента likes или все его содержимое, типа кнопки и обработки клика перенести в контейнер или просто отрендерить Likes внутри контейнера? Если второе, то тогда какой смысл реализовывать addLike в контейнере?

2017-07-26 21:26 UTC, index01d approved these changes

2017-08-15 17:26 UTC, merged